server:
  container_name: redis-cluster
  build: .
  hostname: server
  net: "host"
  restart: always
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7002:7002"
    - "7003:7003"
    - "7004:7004"
    - "7005:7005"
